services:
  db:
    container_name: leftovers-dev-db
    image: postgres:18.4-alpine3.23
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
volumes:
  postgres_data:
